// Automatically generated by MockGen. DO NOT EDIT!
// Source: gitlab.globoi.com/vendas/sms-router/redis (interfaces: Pool)

package mock

import (
	gomock "github.com/golang/mock/gomock"
	redis "github.com/garyburd/redigo/redis"
)

// Mock of Pool interface
type MockPool struct {
	ctrl     *gomock.Controller
	recorder *_MockPoolRecorder
}

// Recorder for MockPool (not exported)
type _MockPoolRecorder struct {
	mock *MockPool
}

func NewMockPool(ctrl *gomock.Controller) *MockPool {
	mock := &MockPool{ctrl: ctrl}
	mock.recorder = &_MockPoolRecorder{mock}
	return mock
}

func (_m *MockPool) EXPECT() *_MockPoolRecorder {
	return _m.recorder
}

func (_m *MockPool) Get() redis.Conn {
	ret := _m.ctrl.Call(_m, "Get")
	ret0, _ := ret[0].(redis.Conn)
	return ret0
}

func (_mr *_MockPoolRecorder) Get() *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "Get")
}
